### PR TITLE
Fixing Administration Options + UAA Incompatibility problem.

### PR DESCRIPTION
**Pull request by rifatdover**
Rebased branch  develop of PR #261 
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by rifatdover** [comment]
@pascalgrimaud This is from develop branch.
Including all changes from #261

**Comment by pascalgrimaud** [comment]
Thanks @rifatdover

**Comment by deepu105** [comment]
Please change to proper PR title

Thanks & Regards,
Deepu

**Comment by pascalgrimaud** [comment]
Lot of work here, it will be hard to do a review in detail.
I don't know in the JHipster team, who knows UAA well ?
@xetys ? but it seems you're busy to do the review
@ruddell ?

Otherwise, if no one is available, I can take this PR, and simply do some tests

**Comment by rifatdover** [comment]
@pascalgrimaud Around %90 of it Jhispter generated Gateway and Microservices code. Maybe it will be easier if you just compare changes with them.

**Comment by pascalgrimaud** [comment]
Yes I know, but although I'm in core team, there are some options I never test... because JHipster provides so much options :-D
So just be patient, I'll do my best to help in this PR, because I worked a lot with microservices + JWT, so I can have a look on this and learn new stuff

**Comment by rifatdover** [comment]
No problem I just want to help actually Jhipster helped us a lot so we need to also 😄

**Comment by rifatdover** [comment]
Today I realized a problem with this. If I enable resource server configuration Basic Authentication disables for Eureka server. So it seems incomplete.

**Comment by rifatdover** [comment]
Now it is fixed.

**Comment by pascalgrimaud** [comment]
I did some tests:
- `./mvnw clean package -Pprod` -> failed in your current branch

Build without tests:
- `./mvnw clean package -Pprod -DskipTests`
- launch the registry, using uaa profile: `java -Xmx256m -jar target/*.war --spring.profiles.active=swagger,prod,native,uaa` -> the application started but I have a lot of errors, I need an UAA server before starting this
- so I stop the Registry

Starting first UAA:
- in my UAA project, I launch the app, it's waiting a registry

So I don't understand the correct order.

**Comment by pascalgrimaud** [comment]
The issue https://github.com/jhipster/jhipster-registry/issues/148 is opened since july 2017.
No one wants to fix this, and you're the only one @rifatdover 

So I wonder if we should keep UAA option or remove it.
@jdubois : what do you think? What are the stats for UAA ? I'd prefer keeping only 2 options: JWT and OAuth2

**Comment by pascalgrimaud** [comment]
@xetys : you're the original guy who did all UAA code, but today, if you don't have time to fix all theses issues, I suggest to simply remove the option which don't work, or put back to [BETA] tag

As we are in an Open Source project, nothing is mandatory and I understand if you don't have time anymore, so no offence in my message <3

**Comment by rifatdover** [comment]
@pascalgrimaud I will fix the test errors. I forgot to look at them. But about dependency problem please look at my  first comment here : https://github.com/jhipster/jhipster-registry/issues/148

**Comment by rifatdover** [comment]
@pascalgrimaud I fixed test errors. So Now you can successfully package it. 

About startup problems:
UAA is the authentication microservice and registry using it to authenticate users (so in this scenario Registry becomes a discovery client). And as a discovery client, it tries to register and fetch information of microservices registered. At startup tries to register itself to Eureka which is also itself and still not serving endpoints to register, receive error!!! After Web service is up and working it fetches application information as a client and using it. 
So think of a case Registry is down and gateway seeking to find it. 

There is no start order actually. You can start any of it. But registry will be better to start first.

**Comment by ruddell** [comment]
Most of this code is just copied over from the UAA gateway, but it does increase the maintenance of the registry if we have to update this code.

Tested and the packaged war works for UAA (once the UAA is up and registered, and after the registry refreshes its routes you can log in).  Also tested a regular app and an OAuth2 gateway - using the `oauth2` profile is broken and won't startup with the following error:

```
Parameter 0 of constructor in io.github.jhipster.registry.web.rest.UserJWTController required a bean of type 'io.github.jhipster.registry.security.jwt.TokenProvider' that could not be found.
```
Based on [this StackOverflow answer](https://stackoverflow.com/questions/35252262/spring-boot-configuration-skip-registration-on-multiple-profile), it looks like you can't exclude two profiles like you are trying and you will have to create a custom annotation.

**Comment by rifatdover** [comment]
Sorry for my late response. I will look and try to fix it as soon as possible.

**Comment by pascalgrimaud** [comment]
Thanks for your hard work @rifatdover 
But as discussed in the over ticket, we decided to merge https://github.com/jhipster/jhipster-registry/pull/278 which fixed  #148
Don't hesite to test it, hope it will definitely fix this issue with UAA

**Pull request closed without merging**
