### PR TITLE
Should use prod profile config when in prod

### PR DESCRIPTION
**Pull request by maivantan1992**
- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
It would be more logical, yes.
Then, there is no "prod" mode for the registry: there's no database, no cache... In fact it always run in "dev" mode, as it's the same as "prod", at least for the moment.
Did you experience any specific issue here?

**Comment by PierreBesson** [comment]
Indeed this is a bug. Currently the registry was using the dev central-config while in prod mode. Good catch @maivantan1992 !

**Comment by maivantan1992** [comment]
@jdubois Normally we set all profile in production in prod mode, even jhipster registry. And all spring cloud config file we use with post fix -prod to make sure no mistake in configuration that can harm production performance. It's take us a time to debug and check the issue why it cannot read spring cloud config. I think this change will save time for who use prod mode in production to got the issue like us.

**Comment by jdubois** [comment]
Yes makes sense, thanks a lot!! This will be in our next release

**Pull request merged**
