### PR TITLE
Update OAuth2ClientCredentialsService.java

### PR DESCRIPTION
**Pull request by ivan86to**
This is necessary to get the microservices back to work with UAA

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by ivan86to** [comment]
Why dependency org.springframework.security.oauth - spring-security-oauth2 has been removed?

**Comment by mraible** [comment]
@ivan86to That's likely a mistake. It's no longer needed for OAuth 2.0 support is likely the reason. If you need it for UAA, please add it back in.

**Comment by ivan86to** [comment]
Thanks @mraible, I'll add it again to work with UNA, and I'll look for an alternative solution

**Comment by mraible** [comment]
FWIW, the reason we need it for UAA is because Spring Security 5.0 does not authorization server support yet. Here’s a helpful feature matrix: https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Features-Matrix <https://github.com/spring-projects/spring-security/wiki/OAuth-2.0-Features-Matrix>

**Pull request closed without merging**
