### PR TITLE
Fix encryption screen

### PR DESCRIPTION
**Pull request by PierreBesson**
# Before
screen shot 2018-06-19 at 21 06 16

# After
screen shot 2018-06-19 at 21 38 53

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
@PierreBesson @jdubois : if we plan to do a official v5 release tomorrow, we need:
- to merge this
- then merge develop branch into master
- do a release of JHipster Registry
- in generator-jhipster, use the tag instead of develop

**Comment by jdubois** [comment]
yes @pascalgrimaud totally agree! Looks doable! Then do we also upgrade to Finchley.RELEASE here?

**Comment by pascalgrimaud** [comment]
Yes we should try to use release.
Sorry, I need sleep, I can't test or help now...
I can check everything tomorrow morning !

**Comment by jdubois** [comment]
Yes no worries I'm doing tests right now

**Comment by jdubois** [comment]
So I did some pretty quick & nasty hacks to make it work with JHipster 5.... The good news is that this looks OK! I'll work on `develop` and if everything is fine we can migrate to `master`.

**Pull request merged**
