### PR TITLE
Add embedded Spring Cloud Config server

### PR DESCRIPTION
**Pull request by PierreBesson**
Currently, it takes its config from central-config/ .yml and .properties files.

### CODE REVIEW

**Comment by jdubois** [comment]
You have a merge conflict :-)

As you give an example code for "app1" -> can you also give some code for the gateway (we are sure it will be there). Maybe we should have some JHipster property read at startup, and log it in the welcome screen, so we know everything is OK

**Comment by PierreBesson** [comment]
OK, I will resolve the conflict, test it further more and add something to the gateway to test it.

**Comment by PierreBesson** [comment]
This should do the job. It's amazing how much it can do with so few lines of code ! I have done the work on the gateway's test, I just need to convert it to template form.

**Comment by jdubois** [comment]
Looks good!!!

**Pull request merged**
