### PR TITLE
Added a Heroku button

### PR DESCRIPTION
**Pull request by jkutner**
Enables one-click deploy to Heroku (with limitations described in the README)

### CODE REVIEW

**Comment by jdubois** [comment]
I don't think the "password" work at the moment, does it?

**Comment by jkutner** [comment]
@jdubois no it doesn't. But it will once `spring-boot-starter-security` is added to the `pom.xml` (which I plan to document in a microservices section of the Heroku docs). Keeping in the procfile makes the transition easier. But admittedly it could confuse people.

**Comment by jdubois** [comment]
Oh, I had the same idea, to secure it with basic authent. It definitely works, even if I'd rather have some API key + token, but that's basically the same thing in the end.

**Comment by jdubois** [comment]
I just merged it -> can you change the title to "deploy with Heroku"? And anyway all doc should be in jhipster.github.io, otherwise the issue is that the doc doesn't match the released versions (which is the case right now...). The idea is that I merge everything when I do the release.

**Comment by jdubois** [comment]
@jkutner and the "password" makes my app crash:

    java.lang.IllegalArgumentException: Invalid argument syntax: --security.user.password=

**Comment by jkutner** [comment]
@jdubois if the JHIPSTER_PASSWORD env var is not set, you'll get that error. Did you deploy with the button?

I'll change the Procfile to contain `${JHIPSTER_PASSWORD:-"password"}`

**Comment by jdubois** [comment]
Oh sorry I did something wrong, that's my fault !

**Pull request merged**
