### PR TITLE
Jhipster deps

### PR DESCRIPTION
**Pull request by erikkemperman**
Changed https://github.com/jhipster/jhipster-registry/pull/186 to point at `develop` instead of `master`. Thanks for tips and increasing the waiting-period, @pascalgrimaud !

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by erikkemperman** [comment]
One thing to mention: @PierreBesson removed the explicit Springfox version:
https://github.com/jhipster/jhipster-registry/commit/f751c3dae111aa2ee6ea8b987dfd96f420f72a56

But this PR imports the new `jhipster-dependencies` BOM which does include it, pegged at 2.7.0.

However, I compared the effective POM on the develop branch before and after my changes, and in both cases the springfox deps come in at 2.7.0. So I guess the removal of the explicit version, which was at 2.6.1 at the time, was effectively an implicit upgrade to 2.7.0, which now is simply made explicit via `jhipster-dependencies`.

Sorry I'm not articulating that very well, hope you get what I'm trying to say :-)

**Comment by erikkemperman** [comment]
Yay, Travis is green!

**Comment by pascalgrimaud** [comment]
@PierreBesson removed the springfox version, because we encounter this issue https://github.com/jhipster/jhipster-registry/issues/185
But it doesn't change anything

**Comment by erikkemperman** [comment]
Thanks for the info, @pascalgrimaud .

Added a last commit, to put most of the plugin configuration under pluginManagement. I will leave this alone now, pending review.

**Comment by PierreBesson** [comment]
@erikkemperman Great job ! Is it ready to merge ?

**Comment by erikkemperman** [comment]
@PierreBesson More or less, it seems to work but Im trying to improve on a co-dependency issue beteren jhipster server lib and the new module.

**Comment by erikkemperman** [comment]
@PierreBesson FYI my idea for resolving the co-dependency issue is on hold for the moment. But it's minor, and I've just updated this PR to use the latest version of the BOM. So as far as I'm concerned, ready to merge.

**Pull request merged**
