### PR TITLE
 Fix OAuth 2.0 Login

### PR DESCRIPTION
**Pull request by mraible**
This is a WIP. It doesn't work yet, which is why I'm creating this as a draft. Currently, it keeps redirecting back to Keycloak, then back to http://localhost:8761, then back to Keycloak, etc. 

I'm curious to know if this is even required. How is the JHipster Registry typically upgraded between releases? Do you run `jhipster upgrade` on it, create a new project and diff, or manually upgrade bits and pieces like the PR is trying to do?

- [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by mraible** [comment]
The fact that the Travis tests pass makes me think they're not testing this project's OAuth support.

**Comment by jdubois** [comment]
@mraible for me this is the main thing that blocks JHipster 6 - I'm available this week and next week to work on this, is there some time we could work together? If this is needed, of course.

Now for your questions: for each major release we are allowed to "break" stuff, so typically here this will be a major release for JHipster Registry, that will match a major release of JHipster. As JHipster configures everything, for example it pulls the JHipster Registry from Docker, it's all done automatically for end-users.

Of course, there is the problem of upgrading: in this case we're quite lucky, as from the end-user point of view that's just a configuration change, and in fact it's all compatible (I'm currently using JHipster 6 beta with the current JHipster Registry: it all works without me doing anything specific, but that's annoying there are 2 different Spring Security OAuth2 configuration).

**Comment by paulusys** [comment]
im still try to connect with jhipster uaa server, any solution how to connect?

**Comment by jdubois** [comment]
@paulusys this PR is a work in progress, don't expect it to work, you should use a stable version instead

**Comment by mraible** [comment]
I might be able to look at it next week. I'm only working three days though, so might be tough.

**Comment by mraible** [comment]
@jdubois My question still hasn't been answered.

> How is the JHipster Registry typically upgraded between releases? Do you run jhipster upgrade on it, create a new project and diff, or manually upgrade bits and pieces like the PR is trying to do?

**Comment by jdubois** [comment]
@mraible oh sorry, I thought you meant from a end-user point of view!

This is done manually, usually we indeed create a new project and do a diff on all the configuration files, usually there isn't so much to do until you touch the entities and the front-end (which shouldn't be modified normally).

**Comment by mraible** [comment]
I took a look and tried to fix this today, but it still doesn't work. It seems to be a CORS issue, but I made sure Keycloak has `http://localhost:8761` as a web origin and it still doesn't work. When it redirects back to JHipster Registry, the following shows up in the web console:

```
Access to XMLHttpRequest at 'http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth?response_type=code&client_id=jhipster-registry&scope=openid%20address%20email%20jhipster%20offline_access%20phone%20profile&state=hqLy1Zkc6fo9Q69Rh4wSW9QaUy07_uVa6dIxmLDn-xM%3D&redirect_uri=http://localhost:8761/login/oauth2/code/oidc' 
(redirected from 'http://localhost:8761/api/account') from origin 'http://localhost:8761' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
```

**Comment by mraible** [comment]
At this point, I feel like giving up and reverting back to the way we did OAuth authentication with Spring Boot 2.0. It'll still work in Spring Boot 2.1, even though it's deprecated. I don't know enough about JHipster Registry to complete this upgrade. 

I'll close this issue and revert https://github.com/jhipster/jhipster-registry/pull/334.

**Comment by vishal423** [comment]
Can you elaborate on pending issues? I can try spending sometime over this weekend. I see you have removed the branch, can you bring that up again so that I can give this a try?

**Comment by mraible** [comment]
I restored the `fix-oauth2` branch. The current `develop` branch does not work when you start JHipster Registry with the following:

```
SPRING_PROFILES_ACTIVE=dev,oauth2,native,swagger ./mvnw
```

If you merge in `fix-oauth2`, it doesn't work either. I'm not sure why, so I gave up.

**Comment by vishal423** [comment]
@mraible, I have raised PR on `fix-oauth2` branch to fix oauth2 login issue. 

While debugging this, I also observed that basic authentication doesn't work with OAuth2 flow which might be required for eureka clients to register.

**Pull request closed without merging**
