### PR TITLE
chore: upgrade keycloak to 19.0.1

### PR DESCRIPTION
**Pull request by juliensadaoui**
related at #542 

I have direclty upgrade to Keycloack 19.

Please make sure the below checklist is followed for Pull Requests.

- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/main/CONTRIBUTING.md) are followed
- [x] Build Docker is OK
- [x] Check if the JWT authentication works
- [x] Check if the OAuth2 authentication works (keycloak, okta, auth0)
- [x] Check if the registry works with microservices and gateways

### CODE REVIEW

**Comment by juliensadaoui** [comment]
I have tested the registry with several IDP providers (Keycloak, Okta, Auth0) connected to it and it works fine.

**Review by mraible — APPROVED** [review]
I didn't test it, but I believe you. 😊

**Comment by juliensadaoui** [comment]
Bounty claimed at https://opencollective.com/generator-jhipster/expenses/93991

**Comment by pascalgrimaud** [comment]
@juliensadaoui : approved

**Pull request merged**
