### PR TITLE
remove unneeded /tmp volume in dockerfiles

### PR DESCRIPTION
**Pull request by PierreBesson**

### CODE REVIEW

**Comment by PierreBesson** [comment]
It's also in the main generator. Is it useful at all @pascalgrimaud, @jdubois.

**Comment by pascalgrimaud** [comment]
see https://spring.io/guides/gs/spring-boot-docker/
i dont know if it is used or not, but it is there for some reason

**Comment by PierreBesson** [comment]
@pascalgrimmaud I know it's coming from here. It was our initial inspiration. But I'm wondering if it is useful at all :
```
	We added a VOLUME pointing to "/tmp" because that is where a Spring Boot application creates working directories for Tomcat by default. The effect is to create a temporary file on your host under "/var/lib/docker" and link it to the container under "/tmp". This step is optional for the simple app that we wrote here, but can be necessary for other Spring Boot applications if they need to actually write in the filesystem.
```
The only advantage I can think of would be that logs will be written in a file in this volume, so you won't lose logs when the container is recreated.

**Comment by pascalgrimaud** [comment]
sure Pierre ! I'm not against removing it. But we just need to be carefull about it and be sure everything works fine, that's why I pointed the official doc :)

**Pull request merged**
