### PR TITLE
[develop] fix refresh

### LINKED ISSUE #152: Minor issues with refresh
Some minor IHM issues:

**1st issue** :
- go to Eureka > Instances
- select another microservice (another than the 1st microservice)
- activate refresh to 5sec
- after 5sec, the refresh forces the selection back to the 1st microservice
- the selection should stay with the selected microservice

**2nd issue** :
- go to Eureka > History
- select 'Last canceled leases'
- activate refresh to 5sec 
- the result list is back to 'Last registered leases', although 'Last canceled leased' is selected

**3rd issue** :
- go to Eureka > History
- the list is not corrected ordered by 'time'

cc @JulienMrgrd as you coded this part.
No worry, I can have a look later, and try to fix them

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Fix #152

### CODE REVIEW

**Comment by PierreBesson** [comment]
@jdubois could you give merge rights on the registry to @pascalgrimaud and me so that we can work on it together. We are going to merge PRs only on the `develop` branch so you can review the changes before doing any release.

**Comment by jdubois** [comment]
Yes of course - the main reason you shouldn't work on `master` is that the "Heroku button" uses it to deploy de registry to Heroku, so would make issues to all those people. And it seems quite popular.

**Comment by pascalgrimaud** [comment]
Yes, that's why I closed the other PR to do this one, for develop branch

**Comment by PierreBesson** [comment]
So I'm merging this as I confirm this works well for us.

**Pull request merged**
