### PR TITLE
[develop] Improve docker image

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Some improvements for the [jhipster/jhipster-registry](https://hub.docker.com/r/jhipster/jhipster-registry/) image, specially:
- remove the 'touch', following https://github.com/jhipster/generator-jhipster/pull/4671 by @ruddell 
- reduce the number of layers

If possible, can you check my modification @ruddell ?

PS: I love this link: https://store.docker.com/community/images/jhipster/jhipster-registry

### CODE REVIEW

**Comment by jdubois** [comment]
Oh, I love the link too, thanks!
I can merge this whenever you want, this looks OK to me.

**Comment by pascalgrimaud** [comment]
yes I think you can. There will be a new image at Docker Hub: jhipster/jhipster-registry:develop 
So I can check the final size

**Comment by pascalgrimaud** [comment]
It's good!
- size before: 270 MB
- size now: 112 MB

**Comment by jdubois** [comment]
That's insane!!! It's going to be great for our microservices!!

**Pull request merged**
