### PR TITLE
Jhipster deps

### PR DESCRIPTION
**Pull request by erikkemperman**
Use the new `jhipster-dependencies` artifact.

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by erikkemperman** [comment]
Travis failed :-(

I've seen the same error (`Connection reset by peer`) from Travis on my own fork, with exactly the same code, but I restarted and then it somehow passed:
https://travis-ci.org/erikkemperman/jhipster-registry/builds/286083188

 Does this happen more often, or is it just me?

**Comment by erikkemperman** [comment]
Added a commit to remove the cc profile, c.f. https://github.com/jhipster/jhipster-registry/commit/a83349361cbd468809b795089926056b81889654#commitcomment-24885495.

This triggered a rebuild on Travis, but again it fails here while the same commit passes on my fork:
https://travis-ci.org/erikkemperman/jhipster-registry/builds/286135693.

Could anyone restart please? Thanks!

**Comment by jdubois** [comment]
Restarted!

**Comment by erikkemperman** [comment]
@jdubois Thanks! Unfortunately, still the same error `Connection reset by peer`. Was this happening before, or is it something I did? The strange thing is it passes on my fork!

**Comment by jdubois** [comment]
@erikkemperman I don't know if that's your fault, but no I haven't seen this before

**Comment by erikkemperman** [comment]
@jdubois Well, that's... Interesting! I just force-started a new Travis build on the current master, and it failed:
https://travis-ci.org/erikkemperman/jhipster-registry/builds/286173615

So I think it might not be something I did (or made worse) but rather that something else is going on.

Maybe I will have some time tomorrow to try to run Travis locally and see if there's any logs that may help narrow this down... But any ideas would certainly be very welcome!

**Comment by jdubois** [comment]
@erikkemperman it can also be a Travis issue, it's not always very stable

**Comment by erikkemperman** [comment]
Hmm, yeah I guess it must be something like that. Could you please restart one more time? If I'm lucky my PR will go green :-)

**Comment by jdubois** [comment]
Restarted :-)

**Comment by pascalgrimaud** [comment]
@erikkemperman : little tips, you can simply close / reopen the PR, so you can restart the build

**Comment by pascalgrimaud** [comment]
**Important thing**: this PR should be against develop branch and not master branch. The reason is the master branch is used to deploy to Heroku directly

**Comment by erikkemperman** [comment]
Ah! Ok, I'll change that then. Did I miss a hint somewhere? Usually PRs go to master :-)

**Comment by pascalgrimaud** [comment]
@erikkemperman :
- yesterday, there was a network problem, it should be resolved now
- about the random failure today, I'm pretty sure we don't give enough time to let the Registry to start before testing with curl, only sleep 30sec
When I looked the logs, I saw:
`Started JHipsterRegistryApp in 25.924 seconds (JVM running for 26.83)`

We should upgrade to 45sec -> I will do it, as same as merging master into develop, as it's not up-to-date

**Comment by pascalgrimaud** [comment]
Not your fault about the develop branch. Not sure we mentionned it somewhere :laughing:

**Pull request closed without merging**
