### PR TITLE
change sensitiveHeaders in ZuulRouteDTO

### LINKED ISSUE #292: OAuth2 Gateway Management Broken
##### **Overview of the issue**
When attempting to manage the gateway through the JHipster Registry Administration pages, you get a 302 to log in with Keycloak with an invalid_redirect_uri.  OAuth2 microservices work fine.

Originally reported on StackOverflow: https://stackoverflow.com/questions/52258423/jhipster-registry-and-keycloak-cors-error-getting-service-informations

##### **Motivation for or Use Case**
Should work out-of-the-box

##### **Reproduce the error**
Generate an OAuth2 Gateway
```
echo '{ "generator-jhipster": { "promptValues": { "packageName": "com.mycompany.myapp", "nativeLanguage": "en" }, "jhipsterVersion": "5.3.1", "applicationType": "gateway", "baseName": "oauthgway", "packageName": "com.mycompany.myapp", "packageFolder": "com/mycompany/myapp", "serverPort": "8080", "authenticationType": "oauth2", "cacheProvider": "hazelcast", "enableHibernateCache": true, "websocket": false, "databaseType": "sql", "devDatabaseType": "h2Disk", "prodDatabaseType": "mysql", "searchEngine": false, "messageBroker": false, "serviceDiscoveryType": "eureka", "buildTool": "maven", "enableSwaggerCodegen": false, "clientFramework": "angularX", "useSass": true, "clientPackageManager": "npm", "testFrameworks": [], "jhiPrefix": "jhi", "enableTranslation": true, "nativeLanguage": "en", "languages": [ "en" ] } }' > .yo-rc.json
jhipster
``` 
Launch JHipster Registry with `oauth2` profile
Launch Gateway
Navigate to the Loggers page and choose the gateway from the dropdown
In the browser console you can see several CORS errors which are really caused by the redirect URI which uses the gateway's IP instead of localhost.
```
Failed to load http://192.168.0.3:8080/login: Redirect from 'http://192.168.0.3:8080/login' to 'http://localhost:9080/auth/realms/jhipster/protocol/openid-connect/auth?client_id=web_app&redirect_uri=http://192.168.0.3:8080/login&response_type=code&scope=openid%20profile%20email&state=N7PdJ1' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost:8761' is therefore not allowed access.
```
##### **Related issues**
Don't think so

##### **Suggest a Fix**
Couldn't figure out a fix

##### **JHipster Registry Version(s)**

- [x] Checking this box is mandatory (this is just to show you read everything)

### PR DESCRIPTION
**Pull request by MetalMiner**
the sensitive header property must not be null

fix #292

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by PierreBesson** [comment]
@ruddell Can you confirm that this fixes the issue ?

**Comment by PierreBesson** [comment]
@rudell I'm not too familiar with how the gateway works with OAuth2 but it's probably because the gateway also has a zuul proxy inside so the "zuul.sensitiveHeaders" should be set in the gateway properties as well. But you need to keep security in mind when setting this. See https://cloud.spring.io/spring-cloud-netflix/multi/multi__router_and_filter_zuul.html#_cookies_and_sensitive_headers
Also very strangely, setting this property like that:
```
zuul:
  sensitiveHeaders:
```
actually set the sensitive header list to "empty" and thus remove the filtering of Cookie, Set-Cookie and Authorization headers.

**Comment by ruddell** [comment]
I tried setting that config in the gateway, but don't see any difference.  OAuth Gateways already have `Cookie` and `Set-Cookie` in `sensitive-headers`.

Gateway endpoints (aside from health, since it allows partial unauthenticated access) still send a 302 to keycloak login

**Comment by MetalMiner** [comment]
@ruddell what is the exact response header when you try to request the `/management/health` endpoint? Maybe it's a general configuration issue and not a OAuth2 issue...

**Comment by ruddell** [comment]
For the `health` endpoint, the headers are exactly the same as the microservice request (it allows unauthorized requests).  For another endpoint like `loggers`, I get a 302 redirect to keycloak:
```
HTTP/1.1 302 Found
Expires: 0
Cache-Control: no-cache, no-store, max-age=0, must-revalidate
X-XSS-Protection: 1; mode=block
Pragma: no-cache
Location: http://192.168.0.24:8080/login
Date: Thu, 10 Jan 2019 18:32:51 GMT
Connection: keep-alive
X-Content-Type-Options: nosniff
Transfer-Encoding: chunked
```

It looks like if I log into the gateway on port 8080, I can then manage the gateway through the Registry endpoints.  The gateway and registry use different cookies `JSESSIONID_REGISTRY` vs `JSESSIONID` so that might be causing it.  I think we can just document this workaround until someone finds a fix

**Comment by jdubois** [comment]
Thanks @MetalMiner !

**Pull request merged**
