### PR TITLE
Update jhipster dependencies and spring-boot version

### PR DESCRIPTION
**Pull request by clement26695**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by DanielFran** [comment]
@clement26695 I will update on April 1 jhipster-bom to target spring-boot 2.1.4.

**Comment by jdubois** [comment]
I'm merging as this works on my machine, probably because I have a newer jhipster dependencies BOM. We'll need to update to a stable BOM as soon as possible.

**Comment by DanielFran** [comment]
@jdubois This should target then spring-boot 2.1.4?

**Comment by jdubois** [comment]
Yes if the build passes :-(

**Pull request merged**
