### PR TITLE
pull request fixing oauth2 with keycloak

### PR DESCRIPTION
**Pull request by aanno2**
I tried v5.0.2 and run into several problems with the 'oauth2' profile. So I opened #385 . To get the discussion more specific, this is the next version of the proposed patch (the old is at https://github.com/jhipster/jhipster-registry/pull/386).

This time, I fixed the tests and have eliminated (the now deprecated) lib `spring-security-oauth2-autoconfigure`. The keycloak specific stuff is based on https://github.com/thomasdarimont/spring-boot-2-keycloak-oauth-example but substantical extended.

The patch has been successfully tested with Keycloak as OAuth2 server. Users who want to log in need the role 'ROLE_ADMIN' in keycloak. At least this has not worked with v5.0.2 before...

### CODE REVIEW

**Comment by mraible** [comment]
In regular JHipster apps, we don't have anything Keycloak specific. Do these changes still work with Okta and other OIDC providers?

**Comment by aanno2** [comment]
Well, in our project, we use JHipster for building microservices and for them the generated code is fine (i.e. no keycloak specific stuff, expect for a authority mapper). Our scenario is like this:

* Browser-based One Page Application (OPA) will do OpenId with keycloak. Bearer token is send as header with every request to the REST microservice.
* Microservice will retrieve scopes and claims from keycloak UserInfo endpoint (hence the token is not trusted directly but by consulting keycloak).
* In case of microservice to microservice call, we use (keycloak?) 'service account' token.

Hence nothing fancy here, but the scenario is very different from what jhipster-registry needs.

The registry wants to be an oauth2 client (app). The problem is that attribute, claims and endpoints are not 100% standarized in OAuth2 and OpenId. Hence I've got the following:

* `KeycloakLogoutHandler`: Propagates logouts to Keycloak. Necessary because Spring Security 5 (currently) doesn't support end-session-endpoints. May work for other OAuth2 Server if they have the same kind of end-session-endpoint.
* `KeycloakOidcUserService`: This is the logic wheather you want to trust the sent token or use the UserInfo endpoint (both scenarios are valid and possible). It looks like it has some keycloak specific code for 'resource server' case (unused here, as the registry does not act as 'resource server').
* `KeycloakAccessTokenResponseClient`: Keycloak only sets the 'openid' scope on access tokens but spring uses this scope value(s) for deciding if the user info end-point should be used. This problem seems to be Keycloak specific.
* `KeycloakAuthoritiesMapper`: A authorities mapper. You always need one (expect you have only one kind of user (no groups/roles)). May work for other OAuth2 Servers as well.

**Comment by aanno2** [comment]
Perhaps I failed to answer you question in the first try. If your question was: Will this code also work with other OAuth2 Servers, the answer is:

**Comment by aanno2** [comment]
Just as a reminder, here is the state of OAuth2 support.

v4.1.1:
* OAuth2 is working (with keycloak).
* User requires the OAuth2 role 'ROLE_ADMIN' to log in.
* As it is working, I never look into the implementation.

v5.0.2:
* OAuth2 is **not** working with keycloak, at least the OAuth2 role 'ROLE_ADMIN' is **not** honoured.
* From the changes needed for fixing, it is very _unlikely_ that is working with any other OAuth2 Server (but I didn't tried that).
* This pull request fixes OAuth2 for keycloak _in a secure way_.
* I suspect that v5.0.2 **seems** to work because of a test user (admin/admin) loaded at application start. See discussion at #385 and #386 for details.
* The docker image loads some strange test users as well.

**Comment by pascalgrimaud** [comment]
@aanno2 : first of all, thanks for proposing this PR.

The main problem with JHipster Registry today is the same use for : JWT auth, OAuth2 and UAA.
Everything in a single app, so we mixed a lot of codes and it's not good. 

What you saw about In Memory User should be used only for JWT, not for OAuth2.
When you use the Registry with JWT, there is no database, so the user is created in memory, provided by the properties. 

I don't know when I have time to have a look on what you did. I hope someone else from the team will.

**Comment by pascalgrimaud** [comment]
Closing this as @juliensadaoui did a crazy job to sync with JHipster 6+
Everything should work today

**Pull request closed without merging**
