### PR TITLE
Feature/doc api

### PR DESCRIPTION
**Pull request by dajay**
The jhipster-registry exposes the Swagger API definitions of the services just as gateway do.
http://www.jhipster.tech/api-gateway/#documentation

### CODE REVIEW

**Comment by PierreBesson** [comment]
Well done @dajay ! :tada: 

I was actually working on this feature myself : https://github.com/jhipster/jhipster-registry/compare/develop...PierreBesson:swagger-management-api?expand=1. But I got distracted by other things.

I quite like your implementation. I have done some testing and noticed some issues:
- The `#docs` screen doesn't display outside of browsersync (In the dev console, I have `Load denied by X-Frame-Options: http://localhost:8761/swagger-ui/index.html does not permit framing.`). Maybe we can allow this in the Spring Security configuration.
- The `try it out` button doesn't work. Probably a swagger UI CORS/preflight problem ?

**Comment by PierreBesson** [comment]
@dajay Can you add this to `application.yml` :
```

jhipster:
    swagger:
        default-include-pattern: /(api|config)/.*
        title: JHipster Registry API
        description: JHipster Registry API documentation
        version: ${info.project.version}
```
So that we have some metadata on the documentation and include both the eureka and config server endpoints.

**Comment by PierreBesson** [comment]
@dajay I tried your new changes, but it didn't work, when running in dev (localhost:8761), I cannot see microservices docs. However I see them when running the front-end though the webpack dev server.

**Comment by dajay** [comment]
Hello @PierreBesson, thx for your feedback. 
In my localhost:8761 i see my microservices docs, do you have error logs?
You see jhipster-registry api docs?

**Comment by PierreBesson** [comment]
This is the response I get when trying to access a microservice docs.
`401 : { "timestamp" : "2017-09-14T13:36:39.657+0000", "status" : 401, "error" : "Unauthorized", "message" : "Access Denied", "path" : "/services/*/*/v2/api-docs" } http://localhost:8761/services/*/*/v2/api-docs`

**Comment by dajay** [comment]
Authorization header is added to the request http://localhost:8761/services/*/*/v2/api-docs ?

**Comment by dajay** [comment]
Hello @PierreBesson, 3 other developers run the registry with my feature and it's working fine, no 401.
Can you help me to fix the problem?
thx Dj

**Comment by PierreBesson** [comment]
I restarted the build and now it's passing. It also works for me locally. Good job @dajay !

**Comment by jdubois** [comment]
Yes this looks awesome!

**Comment by dajay** [comment]
yeah! thx , my first merge on jhipster , so cool!!!!!!

**Comment by jdubois** [comment]
Yes, congrats :-)

**Pull request merged**
