### PR TITLE
Matching with other micro service TokenProvider

### PR DESCRIPTION
**Pull request by gemron**
now it not be able to manage other micro  services.

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by ruddell** [comment]
The tests fail because we run the `jhipster-registry` docker image without a secret key.  One solution is to to update `.travis.yml` to have that property.

`docker run --name jhipster-registry -p 8761:8761 -e JHIPSTER_SECURITY_AUTHENTICATION_JWT_SECRET='secret-key' -d -t jhipster/jhipster-registry:travis`

This setion of code is not reachable anymore though https://github.com/jhipster/jhipster-registry/blob/develop/src/main/java/io/github/jhipster/registry/JHipsterRegistryApp.java#L95-L99

**Comment by gemron** [comment]
@ruddell 
thank you for your correction. I think this way is more friendly, which can avoid application startup errors. That is, if the user does not set the value, it generates a secretKey for it.

**Comment by PierreBesson** [comment]
Now I'm having doubts about merging this. cc @jdubois

**Comment by jdubois** [comment]
Oh indeed!!! Maybe you could revert the commit to test?

**Pull request merged**
