### PR TITLE
Improve cloud config screen

### PR DESCRIPTION
**Pull request by PierreBesson**
the part that is fixed:
capture du 2017-07-07 18-24-59
---
improved displaying of properties
capture du 2017-07-07 18-16-50
capture du 2017-07-07 18-17-05
capture du 2017-07-07 18-17-19
capture du 2017-07-07 18-17-33

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I tried to find how to colorize the Yaml with Angular4... the colors with registry angularJS1 were better :)

**Comment by jdubois** [comment]
Yes I remember looking for it and it couldn't be done easily! Great work, by the way!

**Comment by deepu105** [comment]
With AngularJS I think I used a code mirror like plugin for that. There are
similar plugin for Angular as well we could try if needed

**Comment by PierreBesson** [comment]
Mayve we can use something like highlight.js to do this : https://highlightjs.org

**Pull request merged**
