### PR TITLE
Upgrade to Angular 2

### PR DESCRIPTION
**Pull request by mohamed2a**
Upgrade the application's base config to Angular 2, only the Home Page works, I didn't check the other pages. I added a HomeComponent karma test.
Related to #98

### CODE REVIEW

**Comment by deepu105** [comment]
Isnt this generated using the latest JHipster?  In that case why wouldn't all the admin part work?

**Comment by mohamed2a** [comment]
I couldn't generate the frontend, I think it should be upgraded manually

**Comment by jdubois** [comment]
I'm having a look but there are so many commits and files changed, it's nearly impossible to understand what's going on...

**Comment by mohamed2a** [comment]
I wanted to make atomic commits, I realize it was not necessary ! What shall I do ?

**Comment by jdubois** [comment]
I should be able to squeeze all your commits when I merge, so that should be OK in the end.

But if you have only the home page working, there's still a lot to be done. I'm not sure when I will the time, I'm working on the back-end part with @JulienMrgrd at the moment, and it's quite complex.

**Comment by mohamed2a** [comment]
I made other changes, now Home, Applications, Replicas and History pages work.

**Comment by jdubois** [comment]
Oh, great!
We're working on pushing the microservices/gateways/monoliths available through Zuul, so anytime soon your front end should be able to also access other apps :-)
You'll need something like what we have on the gateways:

- There's a "route" screen that gives you the current available routes (= the apps that can be seen through the Zuul proxy)
- On the Swagger screen, there is a drop-down list that list all those apps, and which allows to use Swagger on each of them, always going through Zuul

**Comment by PierreBesson** [comment]
@jdubois I'm OK to move add swagger to the registry but I would leave the option to have it on the gateway as it will be useful to develop the frontend.

**Comment by jdubois** [comment]
Yes Pierre:

- those will be optional anyway (you will always have those screens in the
registry, then there will be a flag to generate them or not in the gateways
and monoliths)
- the swagger screen was my example as it's the only one with this feature,
but it makes less sense than the metrics or logs screens, of course


Le 21 mars 2017 6:37 PM, "Pierre Besson" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
Guys sorry I dont have enough time to review this but I guess @jdubois and @PierreBesson are taking good care of that

**Comment by jdubois** [comment]
Yes @deepu105 don't worry, I'm on this with @JulienMrgrd also (and @mohamed2a should join us in Paris soon!)

**Pull request merged**
