### PR TITLE
correct git ssh setup docs

### PR DESCRIPTION
**Pull request by PierreBesson**
Minor edits for git ssh docs in the registry.
It would be great if we could make an "info" button to show/hide this docs.

### CODE REVIEW

**Comment by deepu105** [comment]
I could do that :)

**Comment by deepu105** [comment]
@PierreBesson @jdubois Im gonna work on the UI a bit so ill do this as part of that tomorrow

**Comment by jdubois** [comment]
Be careful I'm working on it too -> I'm doing the 'history' page.
Le 3 mai 2016 5:34 PM, "Deepu K Sasidharan" <notifications@github.com> a
écrit :

**Comment by deepu105** [comment]
Ok then ill watch out for your commits, dont worry ill be doing mostly some
polish first. And i dont have write access here so will be PR anyway :)

**Comment by deepu105** [comment]
@jdubois can you merge this plz?

**Comment by jdubois** [comment]
Done!

**Pull request merged**
