### PR TITLE
Fix for issue #148.

### PR DESCRIPTION
**Pull request by rifatdover**
- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [ ] Tests are added where necessar
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

Now when you enable uaa profile over registry server uaa administration functionalities working.
Please check properly especially for security issues.
- Eureka registration functionality uses Basic Authentication.
- Login uses uaa OAuth.

### CODE REVIEW

**Comment by ruddell** [comment]
I can't seem to log in via the registry login page (maybe I'm missing something, ran with `uaa` profile), but I was able to sign into the gateway then go to the registry and I was authenticated.  For OIDC, [the cookie was renamed](https://github.com/jhipster/jhipster-registry/blob/0e6eeb56992b409f76456fa01dbf07a27f46ab7d/src/main/resources/config/application-oauth2.yml#L43) to prevent this from happening.

The great news is all of the admin pages work as expected.  Very nice work!

**Comment by rifatdover** [comment]
I added custom session cookie name but will not work 👎 
That side work exactly same as gateway :(

**Comment by ruddell** [comment]
Currently, I can only access using the gateway cookie.  We need to be able to log into the registry without accessing the gateway first.

**Comment by rifatdover** [comment]
Yes i do. Did you recompile frontend code?

**Comment by ruddell** [comment]
That was it.  I can sign in with the registry after rebuilding frontend code.  You need to add `/auth` to the webpack proxy config in webpack/webpack.dev.js so you can log in from port 9000.

**Comment by pascalgrimaud** [comment]
Can you work on develop branch instead of master branch plz ?

master branch is out of date, and works only with JHipster 4, spring boot 1.5.x

develop branch works with JHipster 5, spring boot 2

**Comment by rifatdover** [comment]
Closing this PR going to reopen a new one from develop branch.

**Pull request closed without merging**
