### PR TITLE
Remove auto redirect on 401 to fix infinite loop with OAuth2

### PR DESCRIPTION
**Pull request by pascalgrimaud**
Fix https://github.com/jhipster/jhipster-registry/issues/439

- Please make sure the below checklist is followed for Pull Requests.

- [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/main/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
if accepted, I'll do a new release of JHipster Registry

**Comment by mraible** [comment]
I'll test this in the next hour or so.

**Review by mraible — APPROVED** [review]
Tested and confirmed it works with OAuth. I'll try with JWT too.

**Comment by mraible** [comment]
Works with JWT too!

**Comment by pascalgrimaud** [comment]
ok thanks, I'm merging this to release a new version of Registry and prepare the beta.1

**Pull request merged**
