### PR TITLE
Add GCP Deploy Button (using Cloud Run) to Readme

### PR DESCRIPTION
**Pull request by SudharakaP**
Working on https://github.com/jhipster/generator-jhipster/issues/10345, I thought it would be beneficial to add a deploy button to GCP, similar to what we have for Heroku. Especially this will help with the microservice deployments on GCP.  

Will finalize the PR once my testing is done :smile: 

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by SudharakaP** [comment]
There's a problem with adding this button and using Cloud Run since the `app.yaml` file for Heroku clashes with the `app.yaml` for Cloud Run. I've opened an issue for this here; https://github.com/GoogleCloudPlatform/cloud-run-button/issues/112

I am thinking of a solution to this. If anyone can think of a workaround for this problem let me know 😄

**Comment by SudharakaP** [comment]
After some thinking about this, I am closing this since there seems to be some work done on the Cloud Run button side (as per https://github.com/GoogleCloudPlatform/cloud-run-button/issues/112) before we can support this button. I'll add this in the future when that work is completed. 😄

**Comment by PierreBesson** [comment]
I'm not a big fan of supporting this kind of button as we will have to do the support ourselves. When we added the Heroku button, it was supported by @jkutner who was paid by Heroku to work on this kind of stuff but this is my understanding that he changed roles at Heroku.
Apart from the wow factor, I don't think it is supporting any real use case to deploy the registry at the click of a button and we have had almost no feedback about it.
Also the fact that we have to keep a separate develop branch to not break the button by mistake is wasting our time and it's a source of confusion for external contributors.

**Comment by SudharakaP** [comment]
@PierreBesson : Agreed. Thanks for the info. Thought it would be nice to have one since we have one already for Heroku. :smile:

**Pull request closed without merging**
