### PR TITLE
Add dashboard

### LINKED ISSUE #56: Registry home dashboard
The current home screen is kind of blank, I would like to add a dashboard with some relevant info about apps, replicas etc so that you get a overview, kind of like the spring registry dashboard. @jdubois what do you think? shall I do it?

### PR DESCRIPTION
**Pull request by deepu105**
Add a dashboard overview on home page
image

@jdubois what do you think?

fix #56

### CODE REVIEW

**Comment by jdubois** [comment]
@deepu105 I'm mostly thinking you are crazy :-)
I need to test but yes definitely +1 for me!

**Comment by deepu105** [comment]
Im just bored :) so finding something interesting to keep me occupied :P

Thanks & Regards,
Deepu

**Comment by jdubois** [comment]
We also have quite a lot of opened tickets :-D

**Comment by deepu105** [comment]
Im going through them as well :) but most are enhancements that someone
wanted to do

Thanks & Regards,
Deepu

**Pull request merged**
