### PR TITLE
only fetch registry when using uaa

### PR DESCRIPTION
**Pull request by ruddell**
related to discussion at bottom of #278

- Please make sure the below checklist is followed for Pull Requests.

- [x] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [x] Tests are added where necessary
- [x] Documentation is added/updated where necessary
- [x] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by PierreBesson** [comment]
I'm not sure but I think it would be nice to have the fetch-registry behavior for JWT as well. It's just that this does throw a stacktrace.

**Comment by ruddell** [comment]
There have been many StackOverflow questions in the last month asking why UAA+Registry doesn't work so I'd love to get this released in the near future.

I couldn't figure out how to hide the error (or print it nicely), if anyone has ideas here please help.

**Comment by jdubois** [comment]
OK but I'm not sure I can merged `develop` into `master` easily, last time I checked I had errors at start up.
I'm testing again.

**Comment by jdubois** [comment]
Oh its looks like it's working -> let me merge everything into develop, and if the Docker image works, I'll release it into master

**Pull request merged**
