### PR TITLE
Update dependencies and sync build with JHipster 6

### PR DESCRIPTION
**Pull request by mraible**
This is an attempt to update dependencies and sync the build process with JHipster 6 in order to [release v5.0](https://github.com/jhipster/jhipster-registry/issues/353) of this project.

Currently blocked by the fact that https://github.com/jhipster/jhipster-registry/pull/346 was merged into `master` rather than the `develop` branch, so tests are failing to compile.

- [ ] [Travis tests](https://travis-ci.org/jhipster/jhipster-registry/pull_requests) are green
- [ ] Tests are added where necessary
- [ ] Documentation is added/updated where necessary
- [ ] Coding Rules & Commit Guidelines as per our [CONTRIBUTING.md document](https://github.com/jhipster/jhipster-registry/blob/master/CONTRIBUTING.md) are followed

### CODE REVIEW

**Comment by jdubois** [comment]
Sorry @mraible I'll try to merge and fix everything tomorrow morning

**Comment by jdubois** [comment]
@mraible I fixed the Java build, but I don't understand what happened on the front-end part, and it's all broken now - did you migrate the application to NPM?

**Comment by mraible** [comment]
@jdubois I tried to migrate to NPM, but could not complete testing everything because of the JUnit compilation errors.

**Comment by jdubois** [comment]
Oh thanks @mraible - then that is indeed normal! I was afraid I broke something

**Pull request merged**
