### PR TITLE
Allow maven to containerize the application

### PR DESCRIPTION
**Pull request by pascalgrimaud**
I followed this [spring guide](https://spring.io/guides/gs/spring-boot-docker/), as I already do :)
- type `mvn package docker:build` to package + generate a new Docker image
- the image created is : **jhipster/jhipster-registry:dev**
- if you don't like the name or the tag, simply modify it in pom.xml

### CODE REVIEW

**Comment by pascalgrimaud** [comment]
I wonder if we should add this maven plugin (same for gradle) in our main generator-jhipster
Then, it will be easier to containerize our Microservice applications

**Comment by jdubois** [comment]
Yes that would be cool to have in the main generator.
I would like to be able to have a full Docker Compose yml file where I can just start a microservice (and its associated database) in just one Docker command.
Then the next step would be a big Docker Compose file with everything in it: gateway, registry, applications, databases...

**Comment by pascalgrimaud** [comment]
@PierreBesson : let me know if you have already begun to work on it

**Comment by PierreBesson** [comment]
@pascalgrimaud: maybe we can do an issue on the main generator to discuss what we want to do.

**Comment by pascalgrimaud** [comment]
yes good idea thanks !

**Pull request merged**
